server:
  port: 8888
spring:
  application:
    name: sm1234-zuul
zuul:
  routes:
    app:
      path: /app/*
      serviceId: sm1234-article

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
    instance:
      instance-id: zuul.com
      prefer-ip-address: true